### ISSUE TITLE
打开插件页面 但是没有插件显示

### ISSUE THREAD

**Issue by Swais2** [MicroCBer/BetterCEF-Installer#46]
![image](https://user-images.githubusercontent.com/125518656/219225014-5be4d740-d222-4d66-8d10-405f8650c9e5.png)

**Comment by KaNe1k** [comment]
Me too.

**Comment by luoyuanye** [comment]
俺也一样

**Comment by EastMonster** [comment]
BetterNCM 已经停止维护了，但是已经装好的插件还能用。估计作者被网易请喝茶了 :(

**Comment by MicroCBer** [comment]
> BetterNCM 已经停止维护了，但是已经装好的插件还能用。估计作者被网易请喝茶了 :(

暂时还没找我，只是最近网易在起诉各种网易游戏私服作者/开发者/服主，不清楚会不会波及到这边，暂时先关一关
